total_money:
  cron: "*/10 * * * *"
  class: "TotalMoney"
  queue: "default"
calculate_rating:
  cron: "* */6 * * *"
  class: "CalculateRating"
  queue: "default"
statistic_report:
  cron: "*/10 * * * *"
  class: "StatisticReport"
  queue: "default"


